env:
  browser: true
  es2021: true
  node: true
  'react-native/react-native': true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - react-native
  - react-hooks
rules: {
  'comma-dangle': 'off',
  'import/no-extraneous-dependencies': 'off',
  'no-use-before-define': 'off',
  'padded-blocks': 'off',
  'react/jsx-filename-extension': 'off',
  'react/prop-types': 'off',
  'react/style-prop-object': 'off'
}
settings: {
  'import/resolver': {
    'babel-module': {}
  }
}
